# Generated by Django 5.1.5 on 2025-01-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='nome',
        ),
    ]
